# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ABAP_BTP_USER
    env:
      ABAP_USER : ${{ vars.ABAP_BTP_USER }}
      ABAP_PASSWORD : ${{ secrets.ABAP_BTP_PASSWORD }}
      ABAP_CLIENT: ${{ secrets.ABAP_BTP_CLIENT }}
      ABAP_URL : ${{ vars.ABAP_BTP_URL }}
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.ABAP_BTP_URL }}"
    - run: npm ci
    - run: echo 'eslint validation' | npm run lint
    - run: echo 'yes' | npm run deploy
